apiVersion: v2
name: "cray-power-control"
version: 2.1.2
description: "Kubernetes resources for cray-power-control"
home: "https://github.com/Cray-HPE/hms-power-control-charts"
sources:
  - "https://github.com/Cray-HPE/hms-power-control"
dependencies:
  - name: cray-service
    version: "~10.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "~1.1"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: 2.0.0
annotations:
  artifacthub.io/license: "MIT"
