name: Build and Publish Helm charts
on: [push, pull_request, workflow_dispatch]
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-chart-workflows/.github/workflows/build_and_release_charts.yaml@v2
    with:
      artifactory-component: cray-hms-power-control
      target-branch: main
    secrets: inherit
